//Autogenerated header for the Intel4004
#pragma once

#include <stdarg.h>
#include <stddef.h>
#include "settings.hpp"
#ifndef NO_CPPSTD
#include <string>
#include <vector>

#endif
#include "AddressInfo.hpp"
#include "AddressInfos.hpp"
#include "bitset.hpp"

class Intel4004
{
   public:   //our internal CPU memory (registers, PC ..)
   uint8_t memory[17] = {};

   Intel4004();

   //function pointer
   typedef void (Intel4004::*op)();

void simulate(size_t bytes = 1);
char* display();
#ifndef NO_CPPSTD
std::string json();
#endif
bitset fetch();
/* rom */
bitset rom_mem[4096];
bitset& rom(AddressInfo info);
bitset& rom(bitset index);
#ifndef NO_CPPSTD
void flash_rom(std::vector<bitset> data);
#endif
void flash_rom(bitset* data, size_t length);

/* ram */
bitset ram_mem[2048];
bitset& ram(AddressInfo info);
bitset& ram(bitset index);
#ifndef NO_CPPSTD
void flash_ram(std::vector<bitset> data);
#endif
void flash_ram(bitset* data, size_t length);

/* ram_status */
bitset ram_status_mem[512];
bitset& ram_status(AddressInfo info);
bitset& ram_status(bitset index);
#ifndef NO_CPPSTD
void flash_ram_status(std::vector<bitset> data);
#endif
void flash_ram_status(bitset* data, size_t length);

/* ram_port */
bitset ram_port_mem[32];
bitset& ram_port(AddressInfo info);
bitset& ram_port(bitset index);
#ifndef NO_CPPSTD
void flash_ram_port(std::vector<bitset> data);
#endif
void flash_ram_port(bitset* data, size_t length);

/* rom_port */
bitset rom_port_mem[16];
bitset& rom_port(AddressInfo info);
bitset& rom_port(bitset index);
#ifndef NO_CPPSTD
void flash_rom_port(std::vector<bitset> data);
#endif
void flash_rom_port(bitset* data, size_t length);

void bin(AddressInfo info, char* addr);
void hex(AddressInfo info, char* addr);
void dec(AddressInfo info, char* addr);
   //functions
   bitset get(AddressInfo info);
   void set(bitset data, AddressInfo info);
   void set(bitset data, int nums, const AddressInfo* infos);
   void set(bitset data, bitset& dest);
   template <size_t C>
   void nop();
   template <size_t C>
   void jcn();
   template <size_t C>
   void fim();
   template <size_t C>
   void src();
   template <size_t C>
   void fin();
   template <size_t C>
   void jin();
   template <size_t C>
   void jun();
   template <size_t C>
   void jms();
   template <size_t C>
   void inc();
   template <size_t C>
   void isz();
   template <size_t C>
   void add();
   template <size_t C>
   void sub();
   template <size_t C>
   void ld();
   template <size_t C>
   void xch();
   template <size_t C>
   void bbl();
   template <size_t C>
   void ldm();
   template <size_t C>
   void wrm();
   template <size_t C>
   void wmp();
   template <size_t C>
   void wrr();
   template <size_t C>
   void wr0();
   template <size_t C>
   void wr1();
   template <size_t C>
   void wr2();
   template <size_t C>
   void wr3();
   template <size_t C>
   void sbm();
   template <size_t C>
   void rdm();
   template <size_t C>
   void rdr();
   template <size_t C>
   void adm();
   template <size_t C>
   void rd0();
   template <size_t C>
   void rd1();
   template <size_t C>
   void rd2();
   template <size_t C>
   void rd3();
   template <size_t C>
   void clb();
   template <size_t C>
   void clc();
   template <size_t C>
   void cmc();
   template <size_t C>
   void stc();
   template <size_t C>
   void cma();
   template <size_t C>
   void iac();
   template <size_t C>
   void dac();
   template <size_t C>
   void ral();
   template <size_t C>
   void rar();
   template <size_t C>
   void tcc();
   template <size_t C>
   void daa();
   template <size_t C>
   void tcs();
   template <size_t C>
   void kbp();
   template <size_t C>
   void dcl();

static Intel4004::op ops[256];

char* str = NULL;};